Stop calling `google_common_workspace_rules()`.
The only parts of bazel-common that we need are rule definitions like `javadoc_library`, not [the targets that `google_common_workspace_rules` creates](https://github.com/google/bazel-common/blob/9f8175287d46cdd21accb4b504a612b44c0f0564/workspace_defs.bzl#L59). (This _might_ have been the case from the beginning in cl/421862373, since that CL set up `//third_party` locally to Guice.)

And calling `google_common_workspace_rules()` leads to trouble under macos-latest (as previously in https://github.com/google/guice/commit/17011080a118fc2d23314ccf0d5546ce53e8b650):

```
  ERROR: /Users/runner/work/guice/guice/WORKSPACE:26:30: fetching android_sdk_repository rule //external:androidsdk: Android SDK api level 34 was requested but it is not installed in the Android SDK at /Users/runner/Library/Android/sdk. The api levels found were [36, 35]. Please choose an available api level or install api level 34 from the Android SDK Manager.
  ERROR: Analysis of target '//tools:osgi_wrapper' failed; build aborted: Android SDK api level 34 was requested but it is not installed in the Android SDK at /Users/runner/Library/Android/sdk. The api levels found were [36, 35]. Please choose an available api level or install api level 34 from the Android SDK Manager.
```

RELNOTES=n/a
PiperOrigin-RevId: 957302488